### ISSUE TITLE
Exception : base process constructor failed 

### ISSUE THREAD

**Issue by dtbMilan** [lanylow/rbxfpsunlocker-osx#157]
it was working fine yesterday , no issues at all , then roblox updates today and now its having issues 
<img width="314" alt="Screenshot 2022-11-16 at 12 22 41 PM" src="https://user-images.githubusercontent.com/117329414/202286600-8c5f71e4-9b68-4c4f-8db4-6ff319703105.png">

**Comment by Stxtically** [comment]
same for me at first but then i closed it and i tried again and it worked

**Comment by kyla0001** [comment]
yeah its saying that for me too

**Comment by colwe** [comment]
if you use -r after inserting the line and have roblox closed and submit then open roblox and remove the -r it will work

**Comment by ai-h24** [comment]
So, after each new Roblox update u must use the `-r` command first (while having roblox closed). 

so use: `sudo /Applications/rbxfpsunlocker_osx 0 -r` while roblox is closed. 

then just use the fps unlocker normally like: `sudo /Applications/rbxfpsunlocker_osx 0` or whatever frame rate u usually use. 


note: you only do the "-r" command after every new roblox update, because it needs to re-sign the app to able to unlock the fps again. **and no need to do it each time u wanna unlock ur fps. just the first time after an update.**
