### ISSUE TITLE
Doesn't work on the new arm64 version of Roblox

### ISSUE THREAD

**Issue by Joemackley** [lanylow/rbxfpsunlocker-osx#214]
Running the command without -r brings up base_process constructor failed while running the command with -r corrupts the app file and it refuses to open

**Comment by lanylow** [comment]
Unfortunately I own a mac with an Intel processor, so I can't really make this program compatible with the new ARM builds of Roblox.

**Comment by dewest456** [comment]
Disabling SIP seems to fix the "Roblox cannot be opened" issue. Found this in console.

Now it returns this error:

![CleanShot 2023-07-21 at 13 49 37@2x](https://github.com/lanylow/rbxfpsunlocker-osx/assets/80060707/ff9c8d53-33fe-4b07-8825-b382a017965e)

Anything else I can show that might help fix the problem?

**Comment by lanylow** [comment]
Changes to the source code are required and as I've said earlier I am unable to make them.

**Comment by Zalryn** [comment]
> Changes to the source code are required and as I've said earlier I am unable to make them.

please dude, there are so many of us that are going through this situation, can you atleast find a way?

**Comment by Zalryn** [comment]
> Changes to the source code are required and as I've said earlier I am unable to make them.

That dude had the same issue as me, and many others as well. I'm sure if they experienced the issue a couple months back, or even last week or a few weeks ago, surely you can fix it, no?

**Comment by lanylow** [comment]
Are you actually stupid or do you have some sort of a disability? The title clearly states that this issue is exclusive to Apple Silicon (M1/M2) Macs, and as I wrote in one of my previous comments I only have a Mac with an Intel processor. I cannot run any programs written for Apple Silicon, which means I cannot run the version of Roblox you have and I cannot develop or test programs written for that platform. This tool is completely open-source, so anyone with experience can make it compatible with the new Roblox builds, but as you've noticed no one is willing to do that. If you keep spamming comments I will have to block you.

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
