### ISSUE TITLE
Instead of increasing Roblox's FPS cap, could the FPS unlocker remove the cap entirely?

### ISSUE THREAD

**Issue by YousufSSyed** [lanylow/rbxfpsunlocker-osx#52]

**Comment by lanylow** [comment]
There is a variable that specifies the minimum time each frame has to last, and that's what this program is overwriting. Technically you could just set it to 0, but there is no point because your computer wouldn't be able to render a frame instantly anyway. So answering the question, you could remove it entirely, but there is no reason to do that. There would be no difference between setting the cap to 1000 and 4294967295 because I doubt you would reach either of these frame rates anyway.

**Comment by YousufSSyed** [comment]
@lanylow How does this FPS unlocker work compared to the one available to Windows? As far as I know, that one removes the cap entirely. If not, can you explain exactly how that one works (without getting _too_ technical)? I couldn't find a way to ask on [the repo](https://github.com/axstin/rbxfpsunlocker/releases).

**Comment by lanylow** [comment]
Both windows and mac version work exactly the same way, which I explained in the previous message.

**Comment by YousufSSyed** [comment]
U didn't explain it did that on Windows, but thanks.

**Comment by YousufSSyed** [comment]
@lanylow Well now I'm wondering, why doesn't the Mac FPS unlocker just set it to 10000? Wouldn't that make it easier to use?

**Comment by lanylow** [comment]
Nothing is stopping you from setting it to 10000. Removing the ability to choose what frame rate you want would be a pointless limitation, as I can see people using caps such as 240.

**Comment by wadisongabriel5-boop** [comment]
Fps
