### ISSUE TITLE
about the fps unlocker thingy

### ISSUE THREAD

**Issue by vinishackreal** [lanylow/rbxfpsunlocker-osx#86]
![image](https://user-images.githubusercontent.com/116986791/198858918-94db7b30-57bf-4a4a-918a-48218db02889.png)
hey this message keeps popping up whenever i download it, ive tried it 7 times and it still hasnt changed, how do i fix it ?

**Comment by cull0** [comment]
Hi! In order to fix this, you have to type "sudo ./rbxfpsunlocker_osx <cap>" For example, "sudo ./rbxfpsunlocker 144" would set the FPS to 144 ONLY IF you are using a 144Hz monitor or screen.

From lanylow: 
"... My monitor is 144Hz and my frame rate doesn't go above that, so I guess ventura is locking it to monitor's refresh rate, similarly as older versions locked it to 120 (at least that's what many issues said). Using tools such as Quartz Debug didn't work for me, and there isn't any other known solution to this."

if you are using an iMac or Macbook and the screen isn't the pro display on the brand new Macbook Pro, you should be capped at 60hz or 60 FPS meaning that you cannot set your FPS to 60< (above 60 FPS). If you are capped at a 60hz display, you might need to get a separate monitor which has a refresh rate of 60>. If you get a 144hz monitor you should cap at 144 FPS (if your device can produce 144 FPS) 

:)

**Comment by landlikescomputers** [comment]
how do you know what Hz your macbook is?

**Comment by lanylow** [comment]
For some reason you have a backslash between `rbxfpsunlocker_osx` and `9`.

**Comment by lanylow** [comment]
> how do you know what Hz your macbook is?

Go to Settings > Displays > Refresh rate.

**Comment by vinishackreal** [comment]
do i type "sudo ./rbxfpsunlocker 144" right after? it keeps telling me that the command is invalid

**Comment by lanylow** [comment]
The dot refers to the current folder, the terminal starts in your Home folder by default so the command you sent would work if the file was in your Home folder.
